# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171114_1050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Computer',
        ),
    ]
